context:
  name: lamindb
  version: "1.10.1"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/lamindb-${{ version }}.tar.gz
  sha256: 323acb621ad28ce4d45fac1053f46081fa8e286d85d58c5a017d916a9d3e5573

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=${{ python_min }}
    - lamin_utils ==0.15.0
    - lamin_cli ==1.6.1
    - lamindb_setup ==1.9.0
    - pyyaml
    - pyarrow
    - pandera >=0.24.0
    - typing_extensions !=4.6.0
    - python-dateutil
    - pandas >=2.0.0
    - scipy <1.15.0
    - anndata >=0.8.0,<=0.12.0
    - fsspec
    - python-graphviz
    - psycopg2-binary

tests:
  - python:
      imports:
        - lamindb
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A data framework for biology.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/laminlabs/lamindb

extra:
  recipe-maintainers:
    - hadim
