context:
  name: lamindb
  version: "1.7.1"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/lamindb-${{ version }}.tar.gz
  sha256: bda1684d84a511b0864ec4c5b8d2b748053bfa4cfd61a740675c6eb4707e151b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=${{ python_min }}
    - lamin_utils ==0.15.0
    - lamin_cli ==1.5.3
    - lamindb_setup ==1.7.2
    - pyyaml
    - pyarrow
    - pandera >=0.24.0
    - typing_extensions !=4.6.0
    - python-dateutil
    - pandas >=2.0.0
    - scipy <1.15.0
    - anndata >=0.8.0,<=0.11.4
    - fsspec
    - python-graphviz
    - psycopg2-binary

tests:
  - python:
      imports:
        - lamindb
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A data framework for biology.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/laminlabs/lamindb

extra:
  recipe-maintainers:
    - hadim
